pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven {
            url = "https://maven.pkg.github.com/RohanDaCoder/gradle-release-plugin"
            credentials {
                username = System.getenv("GITHUB_ACTOR") ?: ""
                password = System.getenv("GITHUB_TOKEN") ?: ""
            }
        }
    }
}

rootProject.name = 'lspskript'

// The LSP backend plugin lives in the skript-lsp subproject.
include 'skript-lsp'
