services:
  paper:
    image: itzg/minecraft-server:latest
    container_name: lspskript-test
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.11"
      MEMORY: "2G"
      JAVA_VERSION: "21"
    ports:
      - "25565:25565"
      - "30505:30505"
    volumes:
      - ./data:/data
